name: Build and Test

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        node:
          - name: Previous LTS
            version: lts/-1
          - name: LTS
            version: lts/*
          - name: Current
            version: node
    name: Build and test (Node ${{ matrix.node.name }})
    permissions:
      contents: read
      packages: read
    steps:
      - name: Build and test
        uses: myrotvorets/composite-actions/build-test-nodejs@master
        with:
          node-version: ${{ matrix.node.version }}
          registry-url: https://npm.pkg.github.com
