name: Linting

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: ESLint Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            npm.pkg.github.com:443
            nodejs.org:443
            pkg-npm.githubusercontent.com:443
            registry.npmjs.org:443

      - name: Run code style check
        uses: myrotvorets/composite-actions/node-run-script@0b8b877ead5e4e6718786803b91d295017964111
        with:
          registry-url: https://npm.pkg.github.com
          script: lint

  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            npm.pkg.github.com:443
            nodejs.org:443
            pkg-npm.githubusercontent.com:443
            registry.npmjs.org:443

      - name: Run type check
        uses: myrotvorets/composite-actions/node-run-script@0b8b877ead5e4e6718786803b91d295017964111
        with:
          registry-url: https://npm.pkg.github.com
          script: typecheck
